{"uuid": "478318fe-95ee-468f-a313-97e15397a4bd", "children": ["2f5ec504-31cb-475c-8b99-27231409557a"], "befores": [{"name": "setup_driver", "status": "passed", "start": 1705424452291, "stop": 1705424475203}], "afters": [{"name": "setup_driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=120.0.6099.217)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6692E4D02+56194]\n\t(No symbol) [0x00007FF6692504B2]\n\t(No symbol) [0x00007FF6690F76AA]\n\t(No symbol) [0x00007FF6690DE1E9]\n\t(No symbol) [0x00007FF6690DF7CE]\n\t(No symbol) [0x00007FF6690F7CC3]\n\t(No symbol) [0x00007FF6690D0580]\n\t(No symbol) [0x00007FF669172D41]\n\t(No symbol) [0x00007FF669165E40]\n\t(No symbol) [0x00007FF669134A45]\n\t(No symbol) [0x00007FF669135AD4]\n\tGetHandleVerifier [0x00007FF66965D5BB+3695675]\n\tGetHandleVerifier [0x00007FF6696B6197+4059159]\n\tGetHandleVerifier [0x00007FF6696ADF63+4025827]\n\tGetHandleVerifier [0x00007FF66937F029+687785]\n\t(No symbol) [0x00007FF66925B508]\n\t(No symbol) [0x00007FF669257564]\n\t(No symbol) [0x00007FF6692576E9]\n\t(No symbol) [0x00007FF669248094]\n\tBaseThreadInitThunk [0x00007FFBA43A257D+29]\n\tRtlUserThreadStart [0x00007FFBA638AA58+40]\n\n", "trace": "  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\conftest.py\", line 79, in setup_driver\n    web_driver.close()\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1705424496946, "stop": 1705424496953}], "start": 1705424452291, "stop": 1705424496953}