{"uuid": "ba4ec668-3ffd-42d7-a831-21c175fb7de5", "children": ["38c018aa-80c2-4de2-b93e-387a4df9814d"], "befores": [{"name": "setup_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome-headless-shell=123.0.6312.124)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6BAE17032+63090]\n\t(No symbol) [0x00007FF6BAD82C82]\n\t(No symbol) [0x00007FF6BAC1EC65]\n\t(No symbol) [0x00007FF6BAC1AC1A]\n\t(No symbol) [0x00007FF6BAC0D514]\n\t(No symbol) [0x00007FF6BAC0E8F8]\n\t(No symbol) [0x00007FF6BAC0D7FF]\n\t(No symbol) [0x00007FF6BAC0D104]\n\t(No symbol) [0x00007FF6BAC0D021]\n\t(No symbol) [0x00007FF6BAC0B0A8]\n\t(No symbol) [0x00007FF6BAC0B8BC]\n\t(No symbol) [0x00007FF6BAC214AD]\n\t(No symbol) [0x00007FF6BACA3D67]\n\t(No symbol) [0x00007FF6BAC86FDA]\n\t(No symbol) [0x00007FF6BACA3412]\n\t(No symbol) [0x00007FF6BAC86D83]\n\t(No symbol) [0x00007FF6BAC583A8]\n\t(No symbol) [0x00007FF6BAC59441]\n\tGetHandleVerifier [0x00007FF6BB2125AD+4238317]\n\tGetHandleVerifier [0x00007FF6BB24F70D+4488525]\n\tGetHandleVerifier [0x00007FF6BB2479EF+4456495]\n\tGetHandleVerifier [0x00007FF6BAEF0576+953270]\n\t(No symbol) [0x00007FF6BAD8E54F]\n\t(No symbol) [0x00007FF6BAD89224]\n\t(No symbol) [0x00007FF6BAD8935B]\n\t(No symbol) [0x00007FF6BAD79B94]\n\tBaseThreadInitThunk [0x00007FF802F4257D+29]\n\tRtlUserThreadStart [0x00007FF80460AA58+40]\n\n", "trace": "  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\conftest.py\", line 72, in setup_driver\n    web_driver.get(config.baseURL)\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\prade\\PycharmProjects\\allgeo_web_app_pro\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1713859098261, "stop": 1713859111277}], "start": 1713859098261, "stop": 1713859111305}